chat/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("", views.index, name="index"),
    path("<str:room_name>/", views.room, name="room"),
]

djangoSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("chat/", include("chat.urls")),
    path('polls/', include("polls.urls")),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    # eg: /polls/
    # path(route = "", view = views.index, name = "index"),
    path("", views.IndexView.as_view(), name="index"),

    # eg: /polls/2/
    # path(route = "<int:pk>", view = views.detail, name = "detail"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),

    # eg: /polls/2/results
    # path(route = "<int:question_id>/results", view = views.results, name = "results"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),

    # eg: /polls/2/voting
    # path(route = "<int:ques_id>/vote", view = views.vote, name = "vote"),
    path("<int:ques_id>/vote/", views.vote, name="vote"),    
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("published_date")

    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        return (self.pub_date >= timezone.now() - datetime.timedelta(days=1)) == \
            (self.pub_date < timezone.now())
    
    class Meta:
        ordering = ["-pub_date"] #descending

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice = models.CharField(max_length=200)
    tally = models.IntegerField(default=0)

    def __str__(self):
        return self.choice

chat/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "chat/index.html")

def room(request, room_name):
    return render(request, "chat/room.html", {"room_name": room_name})

polls/views.py
from django.shortcuts import get_object_or_404, render
# from django.http import HttpResponse, Http404 
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.db.models import F
from django.views import generic
from django.utils import timezone

from .models import Question, Choice

# https://docs.djangoproject.com/en/4.2/ref/class-based-views/generic-display/

# Create your views here.

# def index(request):
#     # return HttpResponse("Hello World! Polls app index.")
#     latest_question_list = Question.objects.order_by("-pub_date")[:5]
#     context = {"latest_question_list": latest_question_list}  
#     return render(request, "polls/index.html", context)
class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(pub_date__lte = timezone.now()).order_by("-pub_date")[:5]

# def detail(request, question_id):
#     # return HttpResponse("Viewing question %s." % question_id)
#     try:
#         question = Question.objects.get(pk=question_id)
#     except Question.DoesNotExist:
#         raise Http404("Question does not exist")
#     # question = get_object_or_404(Question, pk=question_id)
#     return render(request, "polls/detail.html", {"question": question})    
class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte = timezone.now())

# def results(request, question_id):
#     # response = "Tally for question %s."
#     # return HttpResponse(response % question_id)
#     question = get_object_or_404(Question, pk=question_id)
#     question.refresh_from_db()
#     return render(request, "polls/results.html", {"question": question})
class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"

def vote(request, ques_id):
    # response = "Vote for question %s."
    # return HttpResponse(response % ques_id)
    question = get_object_or_404(Question, pk=ques_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.tally = F("tally") + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

chat/templates/chat/index.html
<!-- chat/templates/chat/index.html -->
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>Chat Rooms</title>
</head>

<body>
    What chat room would you like to enter?<br>
    <input id="room-name-input" type="text" size="100"><br>
    <input id="room-name-submit" type="button" value="Enter">

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function (e) {
            if (e.key === 'Enter') {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function (e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/chat/' + roomName + '/';
        };
    </script>
</body>

</html>

chat/templates/chat/room.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>
<body>
    <textarea id="chat-log" cols="100" rows="20"></textarea><br>
    <input id="chat-message-input" type="text" size="100"><br>
    <input id="chat-message-submit" type="button" value="Send">
    {{ room_name|json_script:"room-name" }}
    <script>
        const roomName = JSON.parse(document.getElementById('room-name').textContent);

        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/chat/'
            + roomName
            + '/'
        );

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            document.querySelector('#chat-log').value += (data.year + ':' + data.message + '\n');
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.key === 'Enter') {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message
            }));
            messageInputDom.value = '';
        };
    </script>
</body>
</html>

polls/templates/polls/detail.html
<Html>

<Head>
</Head>

<Body>
    <!-- {{ question }}
    <h1>{{ question.question_text }}</h1>
    <ul>
        {% for choice in question.choice_set.all %}
        <li>{{ choice.choice }}</li>
        {% endfor %}
    </ul> -->

    <form action="{% url 'polls:vote' question.id %}" method="post">
        <!-- Protection against Cross Site Request Forgeries  when targeting internal URLs-->
        {% csrf_token %}
        <fieldset>
            <legend>
                <h1>{{ question.question_text }}</h1>
            </legend>
            {% if error_message %}
                <p><strong>
                    {{ error_message }}
                </strong></p>
            {% endif %}

            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" 
                    id="choice{{ forloop.counter }}" 
                    value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">
                    {{ choice.choice }}
                </label>
                <br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Vote">
    </form>

    <a href="{% url 'polls:index' %}">Index</a>
</Body>

</Html>

polls/templates/polls/index.html
<Html>

<Head>
</Head>

<Body>
    {% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
        <!-- <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li> -->
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No polls are available.</p>
    {% endif %}
</Body>

</Html>

polls/templates/polls/results.html
<!DOCTYPE html>
<Html>

<Head>
</Head>

<Body>
    <h1>{{ question.question_text }}</h1>

    <ul>
        {% for choice in question.choice_set.all %}
        <li>
            {{ choice.choice }} -- {{ choice.tally }} tall{{ choice.tally|pluralize:'y,ies' }}
        </li>
        {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>

    <a href="{% url 'polls:index' %}">Index</a>
</Body>

</Html>